[package]
name = "common"
version = "0.1.0"
license = "MIT or Apache-2.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
proof_gen = { workspace = true }
plonky2 = { workspace = true }
evm_arithmetization = { workspace = true }
clap = { workspace = true }
thiserror = "1.0.50"
